name: 'Github update changelog action'
description: 'Update the changelog'
author: 'Technology Expertise Team - @rubber-duckies'
inputs:
  release-version:
    required: true
    description: 'Version bump'

runs:
  using: "composite"
  steps:
    - name: Version bump in the changelog file - "${{ inputs.release-version }}"
      shell: bash
      run: |
        echo "Version bump is ${{ inputs.release-version }}"
        pwd
        echo ${{ github.action_path }}
        ls -ltr
#        ${{ github.action_path }}/changelog.sh ${{ inputs.release-version }}
#        cat CHANGELOG.md
